/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#0d150d',
          dim: '#0d150d',
          bright: '#333b32',
          'container-lowest': '#081008',
          'container-low': '#151e15',
          container: '#192219',
          'container-high': '#242c23',
          'container-highest': '#2e372e',
        },
        'on-surface': '#dce5d7',
        'on-surface-variant': '#bbcbb8',
        outline: {
          DEFAULT: '#869583',
          variant: '#3c4a3c',
        },
        'surface-tint': '#3ce36a',
        primary: {
          DEFAULT: '#3fe56c',
          container: '#00c853',
          fixed: '#69ff87',
          'fixed-dim': '#3ce36a',
        },
        secondary: {
          DEFAULT: '#7dffa2',
          container: '#05e777',
          fixed: '#62ff96',
          'fixed-dim': '#00e475',
        },
        tertiary: {
          DEFAULT: '#ffb7ae',
          container: '#ff8d81',
          fixed: '#ffdad6',
          'fixed-dim': '#ffb4ab',
        },
        error: {
          DEFAULT: '#ffb4ab',
          container: '#93000a',
        },
        inverse: {
          surface: '#dce5d7',
          'on-surface': '#2a3329',
          primary: '#006e2a',
        },
        background: '#0d150d',
        'on-background': '#dce5d7',
        'on-primary': '#003912',
        'on-primary-container': '#004c1b',
        'on-secondary': '#003918',
        'on-secondary-container': '#00622e',
        'on-tertiary': '#601410',
        'on-tertiary-container': '#76251f',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#002108',
        'on-primary-fixed-variant': '#00531e',
        'on-secondary-fixed': '#00210b',
        'on-secondary-fixed-variant': '#005226',
        'on-tertiary-fixed': '#410002',
        'on-tertiary-fixed-variant': '#7e2a24',
      },
      fontFamily: {
        display: ['Work Sans', 'sans-serif'],
        h1: ['Work Sans', 'sans-serif'],
        h2: ['Work Sans', 'sans-serif'],
        body: ['Work Sans', 'sans-serif'],
        code: ['monospace'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
        h1: ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.01em' }],
        h2: ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'label-caps': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        gutter: '20px',
        'container-margin': '32px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}